'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_ActivateNoteBookPage 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_ActivateNoteBookPage \- select a page on a notebook widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_ActivateNoteBookPage( EZ_Widget *" page )

.SH ARGUMENTS
\fIpage\fR  Specifies a notebook page

.SH DESCRIPTION
A notebook consists several pages. Normally a page is
activated by clicking Button1 on its tab.
.PP
\fBEZ_ActivateNoteBookPage\fR activates the specified page.

.SH "SEE ALSO"
EZ_GetNoteBookPageTab(3)


