'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_BlinkWidget 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_BlinkWidget \- Flash a widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_BlinkWidget(EZ_Widget *" widget ", int " count)
.sp
.SH ARGUMENTS
\fIwidget\fR  Specifies a widget.
.sp
\fIcount\fR  Specifies an integer.
.SH DESCRIPTION
.PP
\fBEZ_BlinkWidget\fR flashes a widget \fIcount\fR number of times.

.SH "SEE ALSO"
EZ_RaiseWidgetWindow(3)

