'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_Configure3DCanvas 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_Configure3DCanvas, EZ_GLConfig \- update the graphics state of a 3D canvas.

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_Configure3DCanvas( EZ_Widget *" canvas )
.BI "void EZ_GLConfig( )"

.SH ARGUMENTS
\fIcanvas\fR  Specifies a 3D canvas widget.

.SH DESCRIPTION
\fBEZ_Configure3DCanvas\fR update the graphics state variables for
a 3D canvas widget.
.PP
\fBEZ_GLConfig\fR update the graphics state variables of the current
active 3D canvas.


.SH "SEE ALSO"
EZ_Set3DCanvas(3)
.br



