'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  EZ_CopyTransposeMatrix 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_CopyVector \- copy one 4-vector to another

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_CopyVector( EZ_Vector " des ", EZ_Vector " src )

.SH ARGUMENTS
\fIsrc\fR specifies a source vector.
.sp
\fIses\fR specifies the destination vector.

.SH DESCRIPTION
\fBEZ_CopyMatrix\fR copies vector \fIsrc\fR to \fIdes\fR.

.SH "SEE ALSO"
EZ_CopyMatrix(3) 



