'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_ClearLcd  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_ClearLcd \- clear a LCD widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_ClearLcd(EZ_Widget *" lcd)
.sp
.SH ARGUMENTS
\fIlcd\fR  Specifies a LCD widget.
.sp
.SH DESCRIPTION
.PP
\fBEZ_ClearLcd\fR erases the display of an LCD widget.

.SH "SEE ALSO"
EZ_SetLcdString(3), EZ_SetLcdInteger(3), EZ_SetLcdNDigits(3), 
EZ_SetLcdFontSize(3), EZ_SetLcdForeground(3), EZ_SetLcdBackground(3)

