'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_CreateTreeNode 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_CreateTreeNode  \- create a tree node

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_TreeNode  *EZ_CreateTreeNode(EZ_TreeNode *" parent ", EZ_Item *" item )


.SH ARGUMENTS
\fIparent\fR  Specifies a parent node.
.sp
\fIitem\fR  Specifies a display item.

.SH DESCRIPTION
.PP
\fBEZ_CreateTreeNode\fR allocates a tree node using the specified data.

.SH "SEE ALSO"
 EZ_CreateItem(3), EZ_CreateDirTree(3)
.br


