'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_DisableBubbleHelp 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_DisableBubbleHelp, EZ_EnableBubbleHelp  \- disable/enable bubble help

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_EnableBubbleHelp(" void )
.BI "void  EZ_DisableBubbleHelp(" void )

.SH DESCRIPTION
.PP
\fBEZ_DisableBubbleHelp\fR Disable the bubble help for an EZWGL
application. Bubble help is enabled by default.
.PP
\fBEZ_EnableBubbleHelp\fR enable the bubble help.
.SH "SEE ALSO"
EZ_DisableHighlight(3), EZ_DisableLabelOffset(3), EZ_DisableSliderDepression(3)
.br



