'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_DisplayWidget 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_DisplayWidget \- display a widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_DisplayWidget( EZ_Widget " *widget )
.BI "void EZ_DisplayWidgetUnderPointer( EZ_Widget " *widget ", int " xoff ", int " yoff )

.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ widget.
.sp
\fIxoff, yoff\fR Specifies an offset.
.SH DESCRIPTION
.PP
\fBEZ_DisplayWidget\fR makes a widget visible. It computes the
geometry of a widget, creates a window for widget and maps it.
If widget has any children widgets, it display them recursively.
.sp
If \fBEZ_DisplayWidget\fR is called on an internal widget
whose parent is not yet displayed, it will display the whole
widget tree.
.PP
\fBEZ_DisplayWidgetUnderPointer\fR behaves similarly, except it
moves the location of the widget window to the location of the
current mouse pointer.  The offset is used to set the widow 
location relative to the mouse pointer. It is interpreted as the following.
When positive, it is the distance between the UL corner and the mouse pointer,
when negative, the absolute value is the distance between the LR corner of
the widget window and the mouse pointer; when both are 0, the widget window
will be centered around the mouse pointer.

.SH "SEE ALSO"
EZ_CreateWidget(3), EZ_DestroyWidget(3), EZ_DrawWidget(3)


