'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_DisableHighlight 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_DisableHighlight, EZ_EnableHighlight  \- disable/enable widget highlight

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_EnableHighlight(" void )
.BI "void  EZ_DisableHighlight(" void )

.SH DESCRIPTION
.PP
\fBEZ_DisableHighlight\fR Disable widget highlighting. By default,
widget highlighting is enabled. I.e., when pointer enters a widget,
the widget is displayed use a lighter color.
.PP
\fBEZ_EnableHighlight\fR enable widget highlighting.
.SH "SEE ALSO"
EZ_DisableBubbleHelp(3), EZ_DisableLabelOffset(3), EZ_DisableSliderDepression(3)
.br



