'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME 
EZ_DrawRectBorder \- move a scrollbar

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_DrawRectBorder( EZ_Widget *" widget ", Drawable " drawable)


.SH ARGUMENTS
\fIwidget\fR specifies a  widget.
.sp
\fIdrawable\fR specifies a drawable, a window or a pixmap

.SH DESCRIPTION
.PP

\fBEZ_DrawRectBorder\fR renders a rectangle border in drawable. The size and border
characterists is taken from widget.

.SH "SEE ALSO"
EZ_UpdateScrollbar(3)
.br



