'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_DisableSliderDepression 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_DisableSliderDepression, EZ_EnableSliderDepression  \-
disable/enable slider depression

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_DisableSliderDepression(" void )
.BI "void  EZ_EnableSliderDepression(" void )

.SH DESCRIPTION
.PP
\fBEZ_DisableSliderDepression\fR Disables slider depression. Slider
depression is enabled by default. I.e., when  button1 press occurs 
a slider button, the button is displayed uses a sunken border.
.PP
\fBEZ_EnableSliderDepression\fR enables slider depression.
.SH "SEE ALSO"
EZ_DisableBubbleHelp(3), EZ_DisableHighlight(3), EZ_DisableLableOffset(3)
.br



