'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_DestroyWidgetWindows 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_DestroyWidgetWindows \- destroy widget windows

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_DestroyWidgetWindows( EZ_Widget " *widget )

.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ widget.
.sp
.SH DESCRIPTION
.PP
\fBEZ_DestroyWidgetWindows\fR destroies the window of \fIwidget\fR
and the windows of all children widgets.

.SH "SEE ALSO"
EZ_DestroyWidget(3), EZ_DisplayWidget(3), EZ_ReomveWidget(3)
.br

