'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME 
EZ_FixFocusHighlightBorder \- draw or remove keyboard focus border

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_FixFocusHighlightBorder( EZ_Widget *" widget )

.SH ARGUMENTS
\fIwidget\fR specifies a widget.
.sp

.SH DESCRIPTION
.PP
\fBEZ_FixFocusHighlightBorder\fR  draws or removes the keyboard
focus border. This function is meant to be used by programmers
who implements his/her own primitive widget.
.PP

.SH "SEE ALSO"
 EZ_RegisterPrimitiveWidget(3)
.br
 EZ_GetDisplayInfo(3)


