'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetWidgetOrientation \- return the orientation of a widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int EZ_GetWidgetOrientation( EZ_Widget *" widget )

.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ Widget.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetWidgetOrientation\fR  returns the orientation of a container
widget. Orientation is used by the default geometry manager to layout
children widgets. 
.PP

.SH "SEE ALSO"
 EZ_GetWidgetGeometry(3)
.br



