'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetCommunicationWindow 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetCommunicationWindow  \- return the id of the unmapped communication window.

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "Window EZ_GetCommunicationWindow()



.SH DESCRIPTION
.PP
\fBEZ_GetCommunicationWindow\fR returns the unmapped communication 
window of an EZWGL application. Inter-client communication between
EZWGL clients is achieved by changing various properties on this
communication window.

.SH "SEE ALSO"
EZ_DisplayWidget(3)
.br



