'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetRadioButtonGroupID 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetRadioButtonGroupID \- return the group id of a radio button

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int EZ_GetRadioButtonGroupID( EZ_Widget *" rbutton )

.SH ARGUMENTS
\fIrbutton\fR Specifies a radio button.
.sp

.SH DESCRIPTION
Radio buttons are grouped into groups. 
.PP
\fBEZ_GetRadioButtonGroupID\fR returns the group identifier
of a radio button.

.SH "SEE ALSO"
EZ_GetRadioButtonGroupVariableValue(3)


