'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GlobHiddenFiles 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GlobHiddenFiles  \- set an internal flag for globbing


.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int EZ_GlobHiddenFiles(int "yesNo)

.SH ARGUMENTS
\fIyesNo\fR Specifies  a boolean value.

.SH DESCRIPTION
.PP
\fBEZ_GlobHiddenFiles\fR sets the showHidden flag for the internal
glob procedure. It return the value of this flag.
.PP

.SH "SEE ALSO"
EZ_GlobFiles(3)
.br



