'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetLedString 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SetLedString \- retrieve the string currently displayed on an LED widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "char *EZ_GetLedString(EZ_Widget *" led ")
.sp
.SH ARGUMENTS
\fIled\fR  Specifies a LED widget.
.sp
.SH DESCRIPTION
.PP
\fBEZ_GetLedString\fR returns the string currently displayed on an LED
widget.

.SH "SEE ALSO"
EZ_SetLedString(3), EZ_QueueLedAction(3), EZ_SetLedFont(3), 
EZ_SetLedPixelSize(3), EZ_SetLedFont(3), EZ_SetLedColorFunction(3)

