'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetWidgetBorder 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetWidgetBorder  \- return widget border characteristics

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_GetWidgetBorder( EZ_Widget" *widget ",  int " *width_ret ", "int " *style_ret )

.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ Widget.
.sp
\fIwidth_ret\fR  Specifies the return for the border width.
.sp
\fIstyle_ret\fR Specifies the return for the border style.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetWidgetBorder\fR returns border characteristics of a widget.

.SH "SEE ALSO"
EZ_GetWidgetGeometry(3)
.br



