'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
 EZ_GetWidgetPixmap \- retrieve the internal pixmap used to label a widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_Pixmap  *EZ_GetWidgetPixmap( EZ_Widget *" widget )

.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ Widget.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetWidgetPixmap\fR  returns the internal pixmap used to
label a widget.
.PP

.SH "SEE ALSO"
 EZ_GetWidgetLabelString(3)
.br



