'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetListTreeWidgetTree 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetListTreeWidgetTree  \- return the root of the tree in a list-tree widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_TreeNode  *EZ_GetListTreeWidgetTree(EZ_Widget *" ltree)


.SH ARGUMENTS
\fIltree\fR  Specifies a list tree widget.

.SH DESCRIPTION
.PP
\fBEZ_GetListTreeWidgetTree\fR returns the root of the tree 
in a list-tree widget.

.SH "SEE ALSO"
EZ_GetListTreeWidgetSelection(3), EZ_CreateTreeNode(3),
EZ_CreateDirTree(3)
.br


