'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetDnDDragSrcXYOffset 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetDnDDragSrcXYOffset  \- return the location of the mouse pointer 
relative to the upper left corner of the drag

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_GetDnDDragSrcXYOffset(int *" x_return ", int *" y_return )


.SH ARGUMENTS
\fIx_return\fR, \fIy_return\fR  Specify the return for the XY offset.

.SH DESCRIPTION
.PP
\fBEZ_GetDnDDragSrcXYOffset\fR  returns the location of the mouse
pointer relative to the upper-left corner of the dragged object.
If DnD is not currently active, it returns the offset corresponding
to the previous drag.

.PP

.SH "SEE ALSO"
EZ_GetDnDDropLocation(3),EZ_WidgetAddDnDDataEncoder(3)
.br



