'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetBubbleHelp "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetBubbleHelp \- return EZWGL's internal bubble help widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_Widget *EZ_GetBubbleHelp(" void )

.SH DESCRIPTION
.PP
\fBEZ_GetBubbleHelp\fR returns EZWGL's internal bubble help
widget (a label).

.SH "SEE ALSO"
EZ_ConfigureWidget(3)
.br



