'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME 
EZ_GetDisplaySize \- return the dimension of the display

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_GetDisplaySize( int *" width_return ", int *" height_return )

.SH ARGUMENTS
\fIwidth_return\fR, \fIheight_return\fR,  specifies the returns for 
the dimension of the display.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetDisplaySize\fR  returns the dimension of the display, in pixels.
.PP

.SH "SEE ALSO"
 EZ_GetDisplay(3)
.br
 EZ_GetDisplayInfo(3)


