'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetListTreeWidgetXYOffset 3 "" EZWGL "EZWGL Functions"
.BS 
.SH NAMEE
EZ_GetListTreeWidgetXYOffset, EZ_SetListTreeWidgetXYOffset 
 \- returns/sets the current XY offset of a
ListTree widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_GetListTreeWidgetXYOffset( EZ_Widget *" widget ", 
.BI "                    int *" x_ret ", int *" y_ret)
.BI "void EZ_SetListTreeWidgetXYOffset( EZ_Widget *" widget ", 
.BI "                    int " x ", int " y)

.SH ARGUMENTS
\fIwidget\fR  Specifies a ListTree widget.
.sp
\fIx_ret\fR,\fIy_ret\fR  Specifies the returns for the XY offset.
.sp
\fIx\fR,\fIy\fR  Specifies the XY offset.
.SH DESCRIPTION
.PP
\fBEZ_GetListTreeWidgetXYOffset\fR returns the current XY offset of a
ListTree widget. The
XY offset is the location of the upper-left corner of the minimal
rectangle that the tree spans, relative to the upper-left corner of
the widget window. 
.PP
\fBEZ_SetListTreeWidgetXYOffset\fR  sets the XY offset.
.PP

.SH "SEE ALSO"
EZ_GetWorkAreaXYOffset(3)


