'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SetHistogramValues 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetHistogramValue \- return a bin value of a histogram

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "float EZ_GetHistogramValue( EZ_Widget *" histogram ", int " binNumber)
        

.SH ARGUMENTS
\fIhistogram\fR  Specifies a histogram widget.
.sp
\fIbinNumber\fR  Specifies a bin index.
.sp

.SH DESCRIPTION
        
.PP
\fBEZ_GetHistogramValue\fR returns the value of the specified bin.

.SH "SEE ALSO"
EZ_SetHistogramValue(3), EZ_SetHistogramColors(3)
.br
EZ_GetHistogramSelection(3)


