'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetWorkAreaNumberOfItems 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetWorkAreaNumberOfItems \- return the number of items in a
WorkArea widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int  EZ_GetWorkAreaNumberOfItems(EZ_Widget *" workarea )

.SH ARGUMENTS
\fIworkarea\fR  Specifies a workarea widget.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetWorkAreaNumberOfItems\fR  returns the number of display items
listed in a WorkArea widget.
.PP

.SH "SEE ALSO"
EZ_WorkAreaFindItemAtXY(3)
.br


