'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetLabelPixmapFromGLImage "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetLabelPixmapFromGLImage \- return the internal pixmap in a GL image

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_Pixmap *EZ_GetLabelPixmapFromGLImage( EZ_GLImage *" image )
.sp

.SH ARGUMENTS
.sp
\fIimage\fR Specifies a GL image.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetLabelPixmapFromGLImage\fR returns the internal pixmap corresponding
to the specified GL image.

.SH "SEE ALSO"
EZ_PutGLImage(3), EZ_CreateGLImage(3)
.br


