'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetInstanceName 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetInstanceName, EZ_GetClassName
\- retrieve the class/instance name of an EZWGL application

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "char *EZ_GetInstanceName(void)
.sp
.BI "char *EZ_GetClassName(void)


.SH DESCRIPTION
.PP
\fBEZ_GetInstanceName\fR returns the instance name of an EZWGL application.
.PP
\fBEZ_GetClassName\fR returns the class name of an EZWGL application.

.SH "SEE ALSO"
EZ_GetWidgetCINames(3)
.br

