'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetWidgetGroupLeader, EZ_SetWidgetGroupLeader 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetWidgetGroupLeader, EZ_SetWidgetGroupLeader,
EZ_SetWidgetTreeGroupLeade \- group widgets

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SetWidgetGroupLeader( EZ_Widget" widget ", EZ_Widget " *leader)
.BI "EZ_Widget *EZ_GetWidgetGroupLeader( EZ_Widget" widget )
.BI "void EZ_SetWidgetTreeGroupLeader( EZ_Widget" widget ", EZ_Widget " *leader)

.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ widget.
.sp
\fIleader\fR  Specifies a widget.

.SH DESCRIPTION


.SH "SEE ALSO"
EZ_GetParentWidget(3)
