'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetWidgetTileOrigin 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetWidgetTileOrigin \- return the tile origin of the background GC.

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_GetWidgetTileOrigin(EZ_Widget " *widget ", int " *x ", int  " y )


.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ widget.
.sp
\fIx, y\fR  Specifies the returns of the tile origin.
.sp

.SH DESCRIPTION
.PP
\fBEZ_WidgetTileOrigin\fR returns origin of the background tile. 

.SH "SEE ALSO"
EZ_GetParentBgGC(3)


