'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetToplevelWidget 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetToplevelWidget \- return the toplevel ancestor

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_Widget *EZ_GetToplevelWidget( EZ_Widget *" widget)


.SH ARGUMENTS
\fIwidget\fR  Specifies a widget.
.sp

.SH DESCRIPTION
.PP
\fBEZ_GetToplevelWidget\fR  returns the toplevel ancestor of a widget.


.SH "SEE ALSO"
EZ_GetParentWidget(3), EZ_GetChildrenWidget(3),
.br


