'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetPopupMenuTitleWidget 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetPopupMenuTitleWidget \- return the title label of a menu

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_GetPopupMenuTitleWidget( EZ_Widget *" menu )

.SH ARGUMENTS
\fImenu\fR  Specifies a popup menu.
.sp

.SH DESCRIPTION

This function returns the title label widget of a menu. 

.SH "SEE ALSO"
EZ_SetWidgetLabelString(3)


