'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_GetBackgroundGC 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_GetBackgroundGC, EZ_GetbackgroundTileGC \- return the background GC.

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int EZ_GetBackgroundGC(EZ_Widget " *widget ", GC " *gc ", unsigned long " *pv,
.BI "                        int " highligt ", int " highlightF )
.BI "int EZ_GetBackgroundTileGC(EZ_Widget " *widget ", GC " *gc ", unsigned long " *pv,
.BI "                          int " highligt ", int " highlightF )


.SH ARGUMENTS
\fIwidget\fR  Specifies an EZ widget.
.sp
\fIgc\fR  Specifies  the return of the background GC.
.sp
\fIpv\fR  Specifies  the return of the pixel value.
.sp
\fIhighlight\fR Specifies whether to return the highlight background GC.
.sp
\fIhighlightF\fR Specifies whether to return the highlight background GC only.
.SH DESCRIPTION
.PP
\fBEZ_GetBackgroundGC\fR returns the GC for rendering the background of 
a widget. It also returns the background pixel value. 
If background tile is used, it returns the background tile GC but
leaves the tile origin undefined. In this case, the background pixel
value is meaningless.
.PP
\fBEZ_GetBackgroundTileGC\fR returns the GC for rendering the background of 
a widget. If background tile is used, it returns the background tile GC 
with the tile origin properly set.
.PP
The returned GC is immediate, it will be modified by EZWGL.

.SH "SEE ALSO"
EZ_GetWidgetTileOrigin(3)

