'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_IdentityMatrix 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_IdentityMatrix, EZ_ZeroMatrix \- initialize a matrix

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_IdentityMatrix( EZ_Matrix " matrix  )

.SH DESCRIPTION
\fImatrix\fR Specifies a matrix.
.SH DESCRIPTION
\fBEZ_IdentityMatrix\fR initializes \fImatrix\fR to
the 4x4 identity matrix.
.PP
\fBEZ_ZeroMatrix\fR initializes  \fImatrix\fR to
 the 4x4 zero matrix.

.SH "SEE ALSO"
EZ_MultMatrix(3), EZ_LoadMatrix(3)



