'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_IsList 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_IsList \- verify the existence of a display list

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int EZ_IsList(int " num )

.SH ARGUMENTS
\fInum\fR Specifies a list number.

.SH DESCRIPTION
\fBEZ_IsList\fR returns 1 if the specified display list exists and
returns 0 otherwise.


.SH "SEE ALSO"
EZ_NewList(3), EZ_DeleteList(3), EZ_CallList(3)



