'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_InstallSymbolicPointer "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_InstallSymbolicPointer, EZ_RetrieveSymbolicPointer \- install/retrieve a symbolic
constant to/from the resource database

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int EZ_InstallSymbolicPointer(char *" name ", void *value)
.sp
.BI "int EZ_RetrieveSymbolicPointer(char *" name ", void **" value_ret)

.SH ARGUMENTS
.sp
\fIname\fR  Specifies a name.
.sp
\fIvalue\fR  Specifies an integer.
.sp
\fIvalue_ret\fR  Specifies the return for value.

.SH DESCRIPTION
.PP
These routines are convenient interface to \fBEZ_InstallSymbol(3)\fR.
It returns -1 if the symbol \fIname\fR is not found or is associated
to some other data type.

.SH "SEE ALSO"
EZ_InstallSymbolicULong(3), EZ_InstallSymbolicInt(3)
.br


