'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_Lightf 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_Lightf, EZ_Lightfv \- set light source parameters

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_Lightf(int " num ", int " attr ", float " values )

.BI "void EZ_Lightfv(int " num ", int " attr ", float *" pvalues )

.SH ARGUMENTS
\fInum\fR Specifies a light source. Must be an integer between 0 and
7.
.sp
\fIattr\fR Specifies which attribute is being updated.
Must be one of EZ_EMISSION, EZ_AMBIENT, EZ_DIFFUSE, EZ_SPECULAR,
EZ_SPOT_DIRECTION, EZ_POSITION, EZ_SPOT_EXPONENT, EZ_SPOT_CUTOFF,
EZ_CONSTANT_ATTENUATION, EZ_LINEAR_ATTENUATION, EZ_QUADRATIC_ATTENUATION.
.sp
\fIvalues\fR Specifies the values for the specified \fIattr\fR.
.sp
\fIpvalues\fR Specifies the values for the specified \fIattr\fR in
an array of floats.

.SH DESCRIPTION
\fBEZ_Lightf/EZ_Lightfv\fR sets values for light properties. 
.sp
If \fIattr\fR is one of EZ_EMISSION, EZ_AMBIENT, EZ_DIFFUSE,
EZ_SPECULAR, EZ_SPOT_DIRECTION or EZ_POSITION, \fIvalues\fR should consist
of 4 floats and \fIpvalues\fR should be an array of 4 floats, with
each in interval [0.0, 1.0].
.sp
If \fIattr\fR is one of EZ_SPOT_EXPONENT, EZ_SPOT_CUTOFF,
EZ_CONSTANT_ATTENUATION, EZ_LINEAR_ATTENUATION, EZ_QUADRATIC_ATTENUATION,
\fIvalues\fR should be a single float point number.

.SH "SEE ALSO"
EZ_Color3f(3), EZ_Normal3f(3), EZ_Vertex3f(3), EZ_Materialf(3),
EZ_DefineLightSrc(3)



