'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_LabelItemSetProperty 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_LabelItemSetProperty \- set the text property of a label item

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_LabelItemSetProperty(EZ_Item *" item ", EZ_TextProperty *" prop )

.SH ARGUMENTS
\fIitem\fR  Specifies a display item.
.sp
\fIprop\fR Specifies a text property.

.SH DESCRIPTION
.PP
\fBEZ_LabelItemSetProperty\fR sets the text property to be used to
display a label item.

.SH "SEE ALSO"
EZ_CreateItem(3), EZ_ConfigureItem(3), EZ_GetTextProperty(3)

