'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_MenuBarDeleteItemAndMenu 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_MenuBarDeleteItemAndMenu  \- delete an item and its associated menu on a menubar


.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_MenuBarDeleteItemAndMenu(EZ_Widget *" mbar ", char *" item )

.SH ARGUMENTS
\fImbar\fR  Specifies a menubar widget.
.sp
\fIitem\fR  Specifies an item label.
.sp

.SH DESCRIPTION
.PP
\fBEZ_MenuBarDeleteItemAndMenu\fR  deletes the item labeled
by \fIitem\fR and its associated menu on a menubar.

.PP

.SH "SEE ALSO"
EZ_CreateWidget(3), EZ_MenuBarFindItemAndMenu(3)
.br



