'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_MenuBarDeleteItem 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_MenuBarDeleteItem  \- delete an item on a menubar


.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_MenuBarDeleteItem(EZ_Widget *" mbar ", char *" item )

.SH ARGUMENTS
\fImbar\fR  Specifies a menubar widget.
.sp
\fIitem\fR  Specifies an item label.
.sp

.SH DESCRIPTION
.PP
\fBEZ_MenuBarDeleteItem\fR  deletes the item labeled
by \fIitem\fR on a menubar. 

.PP

.SH "SEE ALSO"
EZ_CreateWidget(3), EZ_MenuBarFindItem(3)
.br



