'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_OnOffSecretEntry 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_OnOffSecretEntry \- turn on/off a secret entry


.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_OnOffSecretEntry( EZ_Widget *" entry ", int " onoff )

.SH ARGUMENTS
\fIentry\fR  Specifies an entry widget.
.sp
\fIonoff\fR  Specifies  1 or 0.

.SH DESCRIPTION
.PP
\fBEZ_OnOffSecretEntry\fR turns on/off a secret entry. In a secret
entry, the text entered are displayed as a series of "*"s.

.SH "SEE ALSO"
EZ_SetEntryString(3), EZ_EntryEditKillRegion(3)



