'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_Ortho 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_Ortho \- multiply the current matrix by an orthogonal projection matrix

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_Ortho(float " left ", float " right ", float " bottom, 
.BI "                float " top ", float " near ", float " far )

.SH ARGUMENTS
\fIleft\fR ,\fIright\fR  Specify the coordinate of the left and right clipping planes.
.sp
\fIbottom\fR ,\fItop\fR  Specify the coordinate of the bottom and top clipping planes.
.sp
\fInear\fR ,\fIfar\fR  Specify the near and far depth clipping planes.

.SH DESCRIPTION
\fBEZ_Ortho\fR generates an orthogonal projection matrix and
multiplies the current top matrix by this matrix.

.SH "SEE ALSO"
EZ_Rotate(3), EZ_Translate(3), EZ_LookAt(3), EZ_Frustum(3),
EZ_MultMatrix(3), EZ_MatrixMode(3), EZ_Perspective(3)



