'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_PrintStandardOptions 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_PrintStandardOptions  \- print EZWGL standard options to standard error


.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_PrintStandardOptions("void )

.SH DESCRIPTION
.PP
\fBEZ_PrintStandardOptions\fR prints the list of standard
EZWGL command line options to stderr.
.PP

.SH "SEE ALSO"
EZ_GetApplicationResource(3)
.br



