'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  EZ_PushMatrix 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
 EZ_PushMatrix \- push down the current matrix stack

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_PushMatrix(" void )


.SH DESCRIPTION
\fBEZ_PushMatrix\fR pushes down the current matrix stack, duplicating
the current matrix on the stack.


.SH "SEE ALSO"
EZ_PopMatrix(3), EZ_Rotate(3), EZ_MultMatrix(3), 
EZ_LoadMatrix(3), EZ_IdentityMatrix(3), EZ_MatrixMode(3)



