'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH  EZ_PopMatrix 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
 EZ_PopMatrix \- pops the current matrix stack

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_PopMatrix(" void )


.SH DESCRIPTION
\fBEZ_PopMatrix\fR pops the current matrix stack, removing
the top matrix on the stack.


.SH "SEE ALSO"
EZ_PushMatrix(3), EZ_Rotate(3), EZ_MultMatrix(3), 
EZ_LoadMatrix(3), EZ_IdentityMatrix(3), EZ_MatrixMode(3)



