'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_RaiseWidgetWindow 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_RaiseWidgetWindow \- Raise widget window

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_RaiseWidgetWindow(EZ_Widget *" widget)
.sp
.SH ARGUMENTS
\fIwidget\fR  Specifies a widget.

.SH DESCRIPTION
.PP
If the widget window is obscured, \fBEZ_RaiseWidgetWindow\fR 
raises the window.

.SH "SEE ALSO"
EZ_DisplayWidget(3)

