'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_Shutdown 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_Shutdown \-shutdown EZWGL


.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_Shutdown(" void )

.SH DESCRIPTION
.PP
\fBEZ_Shutdown\fR shuts down EZWGL. It releases all the resources
allocated for the relevant EZWGL application and close the
X server connection.
.PP

.SH "SEE ALSO"
EZ_DestroyWidget(3), EZ_Initialize(3)
.br



