'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SSheetInsertRegionString 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SSheetInsertRegionString \- insert some cells into a spread sheet widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SSheetInsertRegionString( EZ_Widget *" ssheet ", int " row ", int "col ", char *" str);

        
.SH ARGUMENTS
\fIssheet\fR  Specifies a spread sheet widget.
.sp
\fIrow, col\fR  Specify a cell index.
.sp
\fIstr\fR  Specifies a string.
.sp

.SH DESCRIPTION
        
.PP
\fBEZ_SSheetInsertRegionString\fR insert one or more cells
starting at the specified location. The specified string
will be broken into cells according to the current tab and
newline character.
.PP

.SH "SEE ALSO"
EZ_SSheetGetRegionString(3),  EZ_SSheetSetTabChar(3),
.br
EZ_SSheetInsertItem(3)


