'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SetTreeWidgetRowBg 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SetTreeWidgetRowBg \- set the alternating background colors for a tree widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SetTreeWidgetRowBg( EZ_Widget *" tree ", int " onoff,
.BI "        char *" color1 ", char *" color2)


.SH ARGUMENTS
\fItree\fR Specifies a list tree widget.
.sp
\fIonoff\fR Specifies a boolean value.
.sp
\fIcolor1\fR Specify a color or nil.
.sp
\fIcolor2\fR Specify a color or nil.

.SH DESCRIPTION
\fBEZ_SetTreeWidgetRowBg\fR turns on/off the alternating background
mode. If turns on, neighboring nodes will be displayed using the
alternating colors supplied. Item background color takes precedence
over the background colors specified by this function. I.e., if the
background color of a tree node (item) is set, that color will be
used to render the background of the tree node.

.SH "SEE ALSO"
EZ_GetListTreeWidgetSelection(3)

