'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SwapBuffers 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SwapBuffers \- display the contents of the back buffer

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SwapBuffers( " void )

.SH DESCRIPTION
\fBEZ_SwapBuffers\fR  copies the contents of the backbuffer to the
front buffer, thus make the contents visiable. 


.SH "SEE ALSO"
EZ_SetBackBuffer(3), EZ_DrawBuffer(3), EZ_AutoSelectBackBuffer(3)



