'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SitForALittleBit 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SitForALittleBit \- sleep for a little bit

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SitForALittleBit(unsigned long " useconds )

.SH ARGUMENTS
\fIuseconds\fR  Specifies a length of time, in micro seconds.

.SH DESCRIPTION
.PP
\fBEZ_SitForALittleBit\fR makes the application sleep for
the specified period of time.

.SH "SEE ALSO"
EZ_AddEventHandler(3), EZ_CreateTimer(3)

