'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SetOptionalEntryString 3 "" EZWGL "EZWGL Functions"
.BS 
.SH NAME
EZ_SetOptionalEntryString, EZ_GetOptionalEntryString  \- set/retrieve the textual
string in a combo box.

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_SetOptionalEntryString( EZ_Widget *" entry ", char *" str )
.BI "char  *EZ_GetOptionalEntryString( EZ_Widget *" entry )

.SH ARGUMENTS
\fIentry\fR  Specifies an optional entry widget.
.sp
\fIstr\fR  Specifies a string.

.SH DESCRIPTION
.PP
\fBEZ_SetEntryString\fR replaces the text in an 
optional entry widget with the specified string.
.PP
\fBEZ_GetEntryString\fR returns the text in an optional entry widget.

.SH "SEE ALSO"
EZ_SetEntryString(3), EZ_SetOptionalEntryOptionalItems(3)


