'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SetLcdFontSize  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SetLcdFontSize \- set the font width of an LCD widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SetLcdFontSize(EZ_Widget *" lcd ", int" n)
.sp
.SH ARGUMENTS
\fIlcd\fR  Specifies a LCD widget.
.sp
\fIn\fR  Specifies a positive integer.
.SH DESCRIPTION
.PP
\fBEZ_SetLcdFontWidth\fR sets the font width of an LCD widget. 

.SH "SEE ALSO"
EZ_SetLcdString(3), EZ_SetLcdInteger(3), EZ_SetLcdNDigits(3),
EZ_SetLcdForeground(3), EZ_SetLcdBackground(3)

