'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SetSMeterBackground 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SetStatusMeterBackground \- set the background color of a
status meter.

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void  EZ_SetStatusMeterBackground( EZ_Widget *" smeter ", char " *clr)

.SH ARGUMENTS
\fIsmeter\fR Specifies a status meter widget.
.sp
\fIclr\fR Specifies a color.

.SH DESCRIPTION
\fBEZ_SetStatusMeterBackground\fR sets the background color
of a status meter.
.PP
	
.SH "SEE ALSO"
EZ_SetStatusMeterRange(3), EZ_SetStatusMeterForeground(3)


