'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SSheetDeleteChart 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SSheetDeleteChart \- remove a spread sheet chart

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SSheetDeleteChart( EZ_Widget *" ssheet ", EZ_Item *" chart)


.SH ARGUMENTS
\fIssheet\fR  Specifies a spread sheet widget.
.sp
\fIchart\fR  Specify a chart.

.SH DESCRIPTION
\fBEZ_SSheetDeleteChart\fR removes the specified spread sheet chart.

.PP

.SH "SEE ALSO"
EZ_SSheetGetActiveChart(3), EZ_SSheetMakeChart(3)
.br


