'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SSheetSetActiveCell 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SSheetSGetActiveCell \- set the current active cell

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SSheetSetActiveCell( EZ_Widget *" ssheet ", int " row ", int " col);

        
.SH ARGUMENTS
\fIssheet\fR  Specifies a spread sheet widget.
.sp
\fIrow,col\fR  Specify a cell.
.sp

.SH DESCRIPTION
        
.PP
\fBEZ_SSheetSetActiveCell\fR sets the current active cell.
.PP

.SH "SEE ALSO"
EZ_SSheetGetCell(3),  EZ_SSheetGetActiveCell(3)
.br



