'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_SetLcdNDigits  3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_SetLcdNDigits \- set the size of an LCD widget

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "void EZ_SetLcdNDigits(EZ_Widget *" lcd ", int" n)
.sp
.SH ARGUMENTS
\fIlcd\fR  Specifies a LCD widget.
.sp
\fIn\fR  Specifies a positive integer.
.SH DESCRIPTION
.PP
\fBEZ_SetLcdNDigits\fR sets the size of an LCD widget. 

.SH "SEE ALSO"
EZ_SetLcdString(3), EZ_SetLcdInteger(3), EZ_SetLcdFontSize(3),
EZ_SetLcdForeground(3), EZ_SetLcdBackground(3)

