'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_TreeNodeGetItem 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_TreeNodeGetItem  \- retieve the display item in a tree node

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_Item  *EZ_TreeNodeGetItem(EZ_TreeNode *" node )


.SH ARGUMENTS
\fInode\fR  Specifies a tree node.
.sp

.SH DESCRIPTION
.PP
\fBEZ_TreeNodeGetItem\fR returns the display item associated
with \fInode\fR

.SH "SEE ALSO"
 EZ_CreateItem(3), EZ_CreateTreeNode(3)
.br


