'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_TreeFindNode 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_TreeFindNodeUsingItem  \- search an item in a tree

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "EZ_TreeNode  *EZ_TreeFindNodeUsingItem(EZ_TreeNode *" root ",
.BI "                                        EZ_Item *" item )


.SH ARGUMENTS
\fIroot\fR  Specifies the root node of a tree.
.sp
\fIitem\fR  Specifies a display item.

.SH DESCRIPTION
.PP
\fBEZ_TreeFindNodeUsingItem\fR searches the tree rooted at \fIroot\fR
for a node that containing the display item \fIitem\fR. If found, it 
returns the node, otherwise it returns NULL.

.SH "SEE ALSO"
 EZ_CreateTreeNode(3), EZ_CreateDirTree(3), EZ_TreeFindNode(3)
.br


