'\"
'\" Copyright (c) 1997 Maorong Zou
'\" 
.TH EZ_WidgetIsViewable 3 "" EZWGL "EZWGL Functions"
.BS
.SH NAME
EZ_WidgetIsViewable  \- query if a widget is currently viewable

.SH SYNOPSIS
.nf
.B #include <EZ.h>
.sp
.BI "int  EZ_WidgetIsViewable(EZ_Widget *" widget )


.SH ARGUMENTS
\fIwidget\fR  Specifies a widget.
.sp

.SH DESCRIPTION
.PP
\fBEZ_WidgetIsViewable\fR returns 1 if \fIwidget\fR is
currently viewable and returns 0 if it is not.

.SH "SEE ALSO"
 EZ_WidgetExist(3), EZ_CreateWidget(3)
.br


