MemDebugData(_PIXEL_VALUE_SWAP_,  0,   "_NOTHING_")
MemDebugData(_PIXEL_VALUE_SWAP_,  1,   "_PIXEL_VALUE_SWAP_")
MemDebugData(_ROSTER_,  2,   "_ROSTER_")
MemDebugData(_REGIS_DATA_,  3,   "_REGIS_DATA_")
MemDebugData(_DPY_LIST_,  4,   "_DPY_LIST_")
MemDebugData(_DPY_TOKEN_,  5,   "_DPY_TOKEN_")
MemDebugData(_DPY_TOKENS_,  6,   "_DPY_TOKENS_")
MemDebugData(_GIF_IMAGE_,  7,   "_GIF_IMAGE_")
MemDebugData(_ROW_IMAGE_DATA_,  8,   "_ROW_IMAGE_DATA_")
MemDebugData(_MATRIX_STACK1_,  9,   "_MATRIX_STACK1_")
MemDebugData(_MATRIX_STACK2_,  10,   "_MATRIX_STACK2_")
MemDebugData(_MATRIX_STACK3_,  11,   "_MATRIX_STACK3_")
MemDebugData(_MATERIAL1_,  12,   "_MATERIAL1_")
MemDebugData(_LIGHT_SRC_,  13,   "_LIGHT_SRC_")
MemDebugData(_LMODEL_,  14,   "_LMODEL_")
MemDebugData(_MATRIX_STACK_ENTRY_,  15,   "_MATRIX_STACK_ENTRY_")
MemDebugData(_SPHERE_P_,  16,   "_SPHERE_P_")
MemDebugData(_SPHERE_V3_,  17,   "_SPHERE_V3_")
MemDebugData(_SPHERE_TRIANGLE_,  18,   "_SPHERE_TRIANGLE_")
MemDebugData(_SPHERE_DATA_,  19,   "_SPHERE_DATA_")
MemDebugData(_SPHERE_CUBE_,  20,   "_SPHERE_CUBE_")
MemDebugData(_TEXT_PROP_,  21,   "_TEXT_PROP_")
MemDebugData(_TP_HT_ENTRY_,  22,   "_TP_HT_ENTRY_")
MemDebugData(_ITEXT_LINE_,  23,   "_ITEXT_LINE_")
MemDebugData(_ITEXT_LINE_D_,  24,   "_ITEXT_LINE_D_")
MemDebugData(_ITEXT_LINE_P_,  25,   "_ITEXT_LINE_P_")
MemDebugData(_KILL_BUF_D_,  26,   "_KILL_BUF_D_")
MemDebugData(_KILL_BUF_P_,  27,   "_KILL_BUF_P_")
MemDebugData(_TIMER_,  28,   "_TIMER_")
MemDebugData(_TUBE_DATA_,  29,   "_TUBE_DATA_")
MemDebugData(_TUBE_V3_,  30,   "_TUBE_V3_")
MemDebugData(_NEW_WIDGET_,  31,   "_NEW_WIDGET_")
MemDebugData(_CALL_BACK_,  32,   "_CALL_BACK_")
MemDebugData(_GL_CONTEXT_,  33,   "_GL_CONTEXT_")
MemDebugData(_Z_BUFF_D_,  34,   "_Z_BUFF_D_")
MemDebugData(_B_BUFF_DATA_,  35,   "_B_BUFF_DATA_")
MemDebugData(_R_BUTTON_GP_,  36,   "_R_BUTTON_GP_")
MemDebugData(_EMBEDER_IMAGE_,  37,   "_EMBEDER_IMAGE_")
MemDebugData(_EXECUTOR_COMMAND_,  38,   "_EXECUTOR_COMMAND_")
MemDebugData(_EXECUTOR_ARGS_,  39,   "_EXECUTOR_ARGS_")
MemDebugData(_KEY_EVENT_HT_ENTRY_,  40,   "_KEY_EVENT_HT_ENTRY_")
MemDebugData(_FONT_TABLE_ENTRY_,  41,   "_FONT_TABLE_ENTRY_")
MemDebugData(_FONT_NAME_,  42,   "_FONT_NAME_")
MemDebugData(_WIDGET_ALL_HT_ENTRY_,  43,   "_WIDGET_ALL_HT_ENTRY_")
MemDebugData(_WIDGET_MAPPED_HT_ENTRY_,  44,   "_WIDGET_MAPPED_HT_ENTRY_")
MemDebugData(_BITMAP_HT_ENTRY_,  45,   "_BITMAP_HT_ENTRY_")
MemDebugData(_BITMAP_NAME_,  46,   "_BITMAP_NAME_")
MemDebugData(_ILIST_BOX_D_,  47,   "_ILIST_BOX_D_")
MemDebugData(_ITEXT_D_,  48,   "_ITEXT_D_")
MemDebugData(_PPM_TMP_D_,  49,   "_PPM_TMP_D_")
MemDebugData(_PPM_TMP_IMAGE_D_,  50,   "_PPM_TMP_IMAGE_D_")
MemDebugData(_DITHER_TMP_D_,  51,   "_DITHER_TMP_D_")
MemDebugData(_ENTRY_I_D_,  52,   "_ENTRY_I_D_")
MemDebugData(_ALLOC_COPY_STR_,  53,   "_ALLOC_COPY_STR_")
MemDebugData(_XPM_COLOR_,  54,   "_XPM_COLOR_")
MemDebugData(_XPM_TMP_HT_,  55,   "_XPM_TMP_HT_")
MemDebugData(_XPM_TMP_HT_E_,  56,   "_XPM_TMP_HT_E_")
MemDebugData(_XPM_TMP_IMAGE_D_,  57,   "_XPM_TMP_IMAGE_D_")
MemDebugData(_XPM_TMP_MASK_D_,  58,   "_XPM_TMP_MASK_D_")
MemDebugData(_XPM_CONTENTS_,  59,   "_XPM_CONTENTS_")
MemDebugData(_XPM_CONTENTS_D_,  60,   "_XPM_CONTENTS_D_")
MemDebugData(_LABEL_STRING_,  61,   "_LABEL_STRING_")
MemDebugData(_BUBBLE_STRING_,  62,   "_BUBBLE_STRING_")
MemDebugData(_CONVERT_POLY_,  63,   "_CONVERT_POLY_")
MemDebugData(_PPM_HASH_ENTRY_,  64,   "_PPM_HASH_ENTRY_")
MemDebugData(_DISPLAY_ITEM_,  65,   "_DISPLAY_ITEM_")
MemDebugData(_ITEM_PROPERTY_,  66,   "_ITEM_PROPERTY_")
MemDebugData(_IFLISTBOX_DATA_,  67,   "_IFLISTBOX_DATA_")
MemDebugData(_TREE_NODE_,  68,   "_TREE_NODE_")
MemDebugData(_IWORK_AREA_DATA_,  69,   "_IWORK_AREA_DATA_")
MemDebugData(_PROPERTY_DATA_,  70,   "_PROPERTY_DATA_")
MemDebugData(_DND_LIST_,  71,   "_DND_LIST_")
MemDebugData(_DND_DROP_MESSAGE_,  72, "_DND_DROP_MESSAGE_")
MemDebugData(_DND_DATA_ENCODER, 73, "_DND_DATA_ENCODER")
MemDebugData(_DND_DATA_DECODER, 74, "_DND_DATA_DECODER")
MemDebugData(_SIMPLE_MENU, 75, "_SIMPLE_MENU")
MemDebugData(_INPUT_ID_, 76, "_INPUT_ID_")
MemDebugData(_CBTN_DATA_, 77, "_CBTN_DATA_")
MemDebugData(_BMPM_TMP_D_,78, "_BMPM_TMP_D_")
MemDebugData(_GRID_BAG_D_,79, "_GRID_BAG_D_")
MemDebugData(_FOCUS_RECORD_,80, "_FOCUS_RECORD_")
MemDebugData(_JPEG_IMAGE_,81, "_JPEG_IMAGE_")
MemDebugData(_EZ_MALLOC_,82, "_EZ_MALLOC_")
MemDebugData(_EZ_LED_DATA_,83, "_EZ_LED_DATA_")
MemDebugData(_LED_AT_,84, "_LED_AT_")
MemDebugData(_GEOM_MANAGER_,85, "_GEOM_MANAGER_")
MemDebugData(_U_DIR_TREE_,86, "_U_DIR_TREE_")
MemDebugData(_SYMB_CONST_TB_,87, "_SYMB_CONST_TB_")
MemDebugData(_ITEM_HTABLE_, 88, "_ITEM_HTABLE_")
MemDebugData(_GARBAGE_OBJ_,89, "_GARBAGE_OBJ_")
MemDebugData(_C_MESSAGE_,90, "_C_MESSAGE_")
MemDebugData(_C_MESSAGE_HANDLE_,91, "_C_MESSAGE_HANDLE_")
MemDebugData(_GL_IMAGE_,92, "_GL_IMAGE_")
MemDebugData(_DIR_TNI_INFO_,93, "_DIR_TNI_INFO_")
MemDebugData(_CLIENT_DATA_,94, "_CLIENT_DATA_")
MemDebugData(_WM_HINTS_DATA_,95, "_WM_HINTS_DATA_")
MemDebugData(_MISC_DATA_,96, "_MISC_DATA_")
MemDebugData(_IWH_ITEM_DATA_, 97, "_IWH_ITEM_DATA_")
MemDebugData(_ITRH_ITEM_DATA_, 98, "_ITRH_ITEM_DATA_")
MemDebugData(_IFLBH_ITEM_DATA_, 99, "_IFLBH_ITEM_DATA_")
MemDebugData(_FIG_ITEM_DATA_, 100, "_FIG_ITEM_DATA_")
MemDebugData(_PNG_IMAGE_, 101, "_PNG_IMAGE_")
MemDebugData(_TIFF_IMAGE_, 102, "_TIFF_IMAGE_")
MemDebugData(_ITERM_DATA_, 103, "_ITERM_DATA_")
MemDebugData(_HISTOGRAM_, 104, "_HISTOGRAM_")
MemDebugData(_RES_EDIT_, 105, "_RES_EDIT_")
MemDebugData(_SSHEET_DATA_, 105, "_SSHEET_DATA_")
